### ISSUE TITLE
setting up

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/oapen-suggestion-service#41]
https://github.com/EbookFoundation/oapen-suggestion-service/blob/15f801a19ab5bb5224ffd1698ee137ccfcdb0469/README.md?plain=1#L7

I believe you want `. ./setup.sh`

**Comment by eshellman** [comment]
```
# npm audit report

node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
fix available via `npm audit fix --force`
```

**Comment by eshellman** [comment]
`./all-dev.sh:8: permission denied: ./run-api.sh
[2]  + exit 126   ./run-api.sh`

**Comment by eshellman** [comment]
` ./run-web.sh
zsh: permission denied: ./run-web.sh`

**Comment by eshellman** [comment]
guess I'm not sure where to start

**Comment by celinanperalta** [comment]
Did you run `chmod +x ./[script].sh`  first?

**Comment by eshellman** [comment]
no.

**Comment by eshellman** [comment]
git will preserve  the x bit, you know

**Comment by celinanperalta** [comment]
Assuming you are running this locally on your machine, are you still getting the permission denied error after updating permissions?

**Comment by eshellman** [comment]
yes it worked
